stages:
  - build_stage
  - deploy_stage

.base-rules:
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: $CI_COMMIT_TAG
      when: never

cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  policy: pull-push
  paths:
    - backend/node_modules/
    - frontend/node_modules/
    - frontend/.next
    - frontend/next.config.js
    - package-lock.json

build:
  stage: build_stage
  extends: .base-rules
  script:
    - npm i &&  npm run build 
  cache:
    <<: *global_cache
    policy: push
  tags:
    - local_runner

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy:
  stage: deploy_stage
  extends: .base-rules
  script:
    - ssh $SSH_USER@$SSH_IP "cd $PATH && git checkout dev && npm i && npm run build && pm2 delete $APPNAME && pm2 start npm --name $APPNAME -- start"
    - pm2 delete $APPNAME
    - pm2 start npm --name $APPNAME -- start
  cache:
    <<: *global_cache
    policy: pull
  tags:
    - local_runner

